import assert from 'node:assert/strict';
import sodium from 'libsodium-wrappers';
import Connection from '../src/connection';
import Websock from '../src/websock';
import {configureSession} from '../src/session';
import {IdPk, SignedId} from '../src/message';
import {RendezvousMessage} from '../src/rendezvous';
(globalThis as any).location = new URL('https://example.test/webclient/');
await sodium.ready;
const server = sodium.crypto_sign_keypair();
const peer = sodium.crypto_sign_keypair();
const box = sodium.crypto_box_keypair();
const id = '123456789';
const config = {id,key:sodium.to_base64(server.publicKey,sodium.base64_variants.ORIGINAL),id_ws:'wss://example.test/webclient/ws/id',relay_ws:'wss://example.test/webclient/ws/relay'};
configureSession({...config,id_ws:'/webclient/ws/id',relay_ws:'/webclient/ws/relay'});
assert.throws(() => configureSession({...config,id_ws:'wss://evil.test/webclient/ws/id'}));
const encoded = (target:string,key:Uint8Array) => IdPk.encode(IdPk.fromPartial({id:target,pk:key})).finish();
const serverSigned = sodium.crypto_sign(encoded(id,peer.publicKey),server.privateKey);
const peerSigned = sodium.crypto_sign(encoded(id,box.publicKey),peer.privateKey);
async function handshake(pk:any,signed:any) {
  const conn = new Connection(); conn._id = id;
  const sends:any[] = [];
  conn._ws = {next:async () => ({signed_id:SignedId.fromPartial({id:signed})}),sendMessage:(v:any) => sends.push(v),setSecretKey:(v:any) => sends.push(v)} as any;
  try { await conn.secure(pk); return sends; } catch (e) { assert.equal(sends.length,0,'Failed identity must not downgrade or send a key'); throw e; }
}
const sends = await handshake(serverSigned,peerSigned);
assert.equal(sends.length,2);
const plain = sodium.crypto_box_open_easy(sends[0].public_key.symmetric_value,new Uint8Array(24),sends[0].public_key.asymmetric_value,box.privateKey);
assert.deepEqual(plain,sends[1]);
await assert.rejects(handshake(undefined,peerSigned));
await assert.rejects(handshake(serverSigned,undefined));
const tampered = serverSigned.slice(); tampered[0] ^= 1;
await assert.rejects(handshake(tampered,peerSigned));
await assert.rejects(handshake(sodium.crypto_sign(encoded('987654321',peer.publicKey),server.privateKey),peerSigned));
await assert.rejects(handshake(serverSigned,sodium.crypto_sign(encoded('987654321',box.publicKey),peer.privateKey)));
await assert.rejects(handshake(serverSigned,sodium.crypto_sign(encoded(id,box.publicKey),server.privateKey)));
const punch = RendezvousMessage.encode(RendezvousMessage.fromPartial({punch_hole_request:{id,nat_type:2,licence_key:config.key}})).finish();
assert.equal(punch[0],66); assert.equal(RendezvousMessage.decode(punch).punch_hole_request!.token,'');
const relay = RendezvousMessage.encode(RendezvousMessage.fromPartial({request_relay:{id,uuid:'test-uuid',licence_key:config.key}})).finish();
assert.equal(relay[0],146); assert.equal(RendezvousMessage.decode(relay).request_relay!.id,id);
(globalThis as any).window = {ArrayBuffer};
(globalThis as any).WebSocket = {OPEN:1,CONNECTING:0};
let closed = false;
const socket = Object.create(Websock.prototype);
socket._websocket = {readyState:1,close:()=>{closed=true}};
socket._status = 'open'; socket._buf = []; socket._secretKey = [sodium.crypto_secretbox_keygen(),0,0];
socket._eventHandlers = {message:()=>{}};
socket._recv_message({data:new Uint8Array([1,2,3]).buffer});
assert.equal(closed,true);
await assert.rejects(socket.next(0));
console.log('Browser security check passed: valid encrypted exchange, failed identity rejection, target and endpoint binding.');
